Linking social account to user
qilin/auth1.protocol.one pull request #16
Opened 2020-03-03 08:12 UTC by Irioth

2020-03-03 15:11 UTC, cheebo requested changes

2020-03-03 15:11 UTC, cheebo commented on pkg/api/apierror/errors.go
> +	fmt.Println(err)
Это временное решение с println или планируется оставить?

2020-03-03 15:11 UTC, cheebo commented on pkg/manager/login.go
> +func (m *LoginManager) AuthLink(token string, userID bson.ObjectId, app *models.Application) error {
было бы хорошо иметь комент к методу с описанием что он делает

2020-03-03 15:11 UTC, cheebo commented on pkg/models/oauth2.go
> +	Social string `query:"social" form:"social"`
хорошо бы добавить комент как в loginform

2020-03-04 05:48 UTC, Irioth commented on pkg/manager/login.go
> +func (m *LoginManager) AuthLink(token string, userID bson.ObjectId, app *models.Application) error {
переименовал в Link, добавил коммент

2020-03-04 05:56 UTC, Irioth commented on pkg/api/apierror/errors.go
> +	fmt.Println(err)
добавил сообщение к ошибке, вообще тут можно получше сделать, но пока просто сообщение к ошибке будет

2020-03-04 06:05 UTC, cheebo approved these changes

2020-03-04 07:29 UTC, cheebo commented
LGTM

2020-03-04 07:50 UTC, merged